**GOAL:**
* If you are a sports enthusiast who occasionally invests in legal betting, this project idea will interest you.
* That’s because analyzing sports statistically helps understand which players or teams offer intense competition and are likely to win.

Import the necessary libraries

In [108]:
'''
Title:Web Scrapping Project: Sports Analytics for America’s National Football League
Author:Jedidah Wavinya
Date: 14 Ocober 2025
'''
#Importing libraries that I will need for webscraping
from bs4 import BeautifulSoup
import requests
import pandas as pd
import requests

In [109]:
#set URL of website in a variable
url = 'https://www.nfl.com/stats/team-stats/'
page = requests.get(url)

In [110]:
#Use BeautifulSoup to extract the HTML content
soup = BeautifulSoup(page.text, 'html.parser')

In [111]:
# Extract the table with the Team data
table = soup.find_all('table')

# Use pandas to read the HTML table into a DataFrame
if table:
    df = pd.read_html(str(table))[0]

    # Display the entire DataFrame
    display(df)
else:
    print("No table found on the page.")

/tmp/ipython-input-1863144812.py:6: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

,Team,Att,Cmp,Cmp %,Yds/Att,Pass Yds,TD,INT,Rate,1st,1st%,20+,40+,Lng,Sck,SckY
0,Browns Browns,249,144,57.8,5.0,1245,5,6,67.8,57,22.9,11,0,35,17,100
1,49ers 49ers,241,161,66.8,7.6,1838,10,7,91.3,90,37.3,21,4,56,13,89
2,Cowboys Cowboys,234,167,71.4,7.1,1658,13,4,102.5,82,35.0,20,4,46,7,36
3,Chargers Chargers,220,149,67.7,7.0,1537,10,4,95.2,72,32.7,18,2,60T,18,97
4,Chiefs Chiefs,213,138,64.8,7.1,1514,11,2,99.0,75,35.2,17,2,49T,10,66
5,Jaguars Jaguars,211,129,61.1,6.3,1324,8,5,81.9,63,29.9,15,3,46,13,82
6,Rams Rams,210,139,66.2,8.0,1684,12,2,105.7,78,37.1,28,3,88T,11,69
7,Saints Saints,207,140,67.6,6.0,1236,6,2,89.0,60,29.0,8,2,87T,11,61
8,Broncos Broncos,206,133,64.6,6.2,1277,9,4,88.2,63,30.6,13,2,52T,6,36
9,Cardinals Cardinals,206,137,66.5,6.2,1282,8,4,88.3,67,32.5,14,2,45,18,119
10,Panthers Panthers,205,128,62.4,5.9,1208,11,5,86.4,68,33.2,16,1,40,10,79
11,Bengals Bengals,205,130,63.4,5.7,1165,10,8,78.6,57,27.8,10,2,64,16,94
12,Titans Titans,202,111,55.0,5.4,1101,3,4,67.3,54,26.7,15,1,47,25,198
13,Giants Giants,197,122,61.9,6.6,1294,7,5,82.3,55,27.9,16,3,52T,16,82
14,Buccaneers Buccaneers,195,129,66.2,7.9,1539,12,1,108.5,67,34.4,24,4,77T,10,74
15,Dolphins Dolphins,191,133,69.6,6.6,1253,11,7,91.4,70,36.6,12,3,47,13,67
16,Raiders Raiders,186,123,66.1,7.3,1350,7,10,77.6,64,34.4,19,2,61T,18,141
17,Colts Colts,183,130,71.0,8.3,1511,8,3,103.4,76,41.5,17,4,75,5,41
18,Bills Bills,180,123,68.3,7.9,1429,11,4,103.2,73,40.6,20,3,51,12,65
19,Patriots Patriots,180,131,72.8,8.5,1522,10,2,111.8,70,38.9,20,2,55,18,55
20,Lions Lions,175,133,76.0,8.0,1393,15,2,122.4,75,42.9,18,2,64T,9,43
21,Eagles Eagles,172,117,68.0,6.8,1172,8,1,100.2,54,31.4,15,3,52,18,97
22,Commanders Commanders,172,108,62.8,7.2,1238,10,2,98.9,56,32.6,13,3,56,14,70
23,Jets Jets,170,113,66.5,6.2,1052,7,1,94.5,55,32.4,10,0,33T,25,187
24,Falcons Falcons,164,103,62.8,7.3,1197,4,3,85.3,56,34.2,16,3,69,7,59
25,Seahawks Seahawks,164,116,70.7,9.5,1556,11,3,115.3,69,42.1,24,6,61T,7,43
26,Ravens Ravens,163,112,68.7,7.6,1240,10,5,98.7,55,33.7,16,2,56,20,142
27,Bears Bears,162,100,61.7,7.4,1206,9,2,97.9,52,32.1,18,3,65T,10,67
28,Texans Texans,148,104,70.3,7.4,1099,8,3,101.2,46,31.1,15,2,50T,12,108
29,Packers Packers,147,103,70.1,8.6,1259,9,2,110.9,57,38.8,18,3,57,9,72
30,Vikings Vikings,146,96,65.8,7.7,1121,8,5,92.9,51,34.9,16,2,81T,21,130
31,Steelers Steelers,140,97,69.3,7.4,1033,10,3,105.4,42,30.0,15,2,80T,9,64

In [112]:
display(df.head())
display(df.info())

,Team,Att,Cmp,Cmp %,Yds/Att,Pass Yds,TD,INT,Rate,1st,1st%,20+,40+,Lng,Sck,SckY
0,Browns Browns,249,144,57.8,5.0,1245,5,6,67.8,57,22.9,11,0,35,17,100
1,49ers 49ers,241,161,66.8,7.6,1838,10,7,91.3,90,37.3,21,4,56,13,89
2,Cowboys Cowboys,234,167,71.4,7.1,1658,13,4,102.5,82,35.0,20,4,46,7,36
3,Chargers Chargers,220,149,67.7,7.0,1537,10,4,95.2,72,32.7,18,2,60T,18,97
4,Chiefs Chiefs,213,138,64.8,7.1,1514,11,2,99.0,75,35.2,17,2,49T,10,66

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Team      32 non-null     object
 1   Att       32 non-null     int64
 2   Cmp       32 non-null     int64
 3   Cmp %     32 non-null     float64
 4   Yds/Att   32 non-null     float64
 5   Pass Yds  32 non-null     int64
 6   TD        32 non-null     int64
 7   INT       32 non-null     int64
 8   Rate      32 non-null     float64
 9   1st       32 non-null     int64
 10  1st%      32 non-null     float64
 11  20+       32 non-null     int64
 12  40+       32 non-null     int64
 13  Lng       32 non-null     object
 14  Sck       32 non-null     int64
 15  SckY      32 non-null     int64
dtypes: float64(4), int64(10), object(2)
memory usage: 4.1+ KB

None

Save the data in to a csv file

In [113]:
df.to_csv('nfl_team_stats.csv', index=False)